/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface Entity {
  text: string
  label: string
  score: number
}

export declare function extractEntities(text: string, labels: Array<string>): Array<Entity>
